default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  port: 5432
  username: transcript_search_dev
  password: password
  database: transcript_search_development_database

# IGNORE THESE FOR NOW
# test:
#   <<: *default
#   username: <%= ENV['DB_USERNAME'] %>
#   password: <%= ENV['DB_PASSWORD'] %>
#   database: myapp_test

# production:
#   <<: *default
#   database: myapp_production
#   username: myapp
#   password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
